# Site settings
title: Yolo on my friend
tag_text: Yolo
description: Loveable single page sites
# Site customizations
style: corbs
logo: assets/images/site/logo.png
images: https://storage.googleapis.com/corbs-foto/yolo
# Build settings
version: v1.16
markdown: kramdown
exclude:
  - "README.md"
  - "BACKLOG.md"
  - "Makefile"
  - "Containerfile"
  - ".yolo-build"
  - "src/"
  - "docs/"
sass:
  style: compressed
