# -----------------------------------------------------------------------------
# Jekyll site settings, see _data/settings.yml for Yolo settings
# -----------------------------------------------------------------------------
# baseurl: The sub-path your site is hosted from, for example: /blog
# -----------------------------------------------------------------------------
baseurl: ""
# -----------------------------------------------------------------------------
# url: The protocol and hostname for your site, for example: https://corbs.io
# -----------------------------------------------------------------------------
url: ""
# -----------------------------------------------------------------------------
# markdown: The markdown processor to use, kramdown is the jekyll default.
# -----------------------------------------------------------------------------
markdown: kramdown
# -----------------------------------------------------------------------------
# exclude: List of files and folders to exclude from jekyll
# -----------------------------------------------------------------------------
exclude:
  - "README.md"
  - "Makefile"
  - "Containerfile"
  - "src/"
  - "docs/"
# -----------------------------------------------------------------------------
# sass_dir: Folder that contains sass/scss files to be processed
# style: compressed or uncompressed css generation
# -----------------------------------------------------------------------------
sass:
  sass_dir: _sass
  style: uncompressed
