# Site settings
title: Solo, a single page Jekyll Theme
tag_text: Solo
description: Solo is a Jekyll theme that supports single-page websites only, but supports them well. Yes, it’s responsive.
# Site customizations
logo: assets/images/logo.png
style: corbs
# Build settings
version: v1.1
sampler: false
markdown: kramdown
exclude:
  - "README.md"
  - "Makefile"
  - "sampler.Containerfile"
  - "solo.Containerfile"
  - ".site-build"
sass:
  style: uncompressed
