# Site settings
title: YoSo, a single page theme
tag_text: YoSo
description: You only single-page once
# Site customizations
logo: assets/images/logo.png
style: corbs
# Build settings
version: v1.1
sampler: false
markdown: kramdown
exclude:
  - "README.md"
  - "Makefile"
  - "sampler.Containerfile"
  - "yolo.Containerfile"
  - ".site-build"
sass:
  style: uncompressed
