# Site settings
title: Yolo on my friend
tag_text: Yolo
description: Loveable single page sites
# Site customizations
style: corbs
# Align content, left, center or right (default is left)
align: left
#logo: assets/images/site/logo.png
images: https://storage.googleapis.com/corbs-foto/yolo
sidebar:
  logo: assets/images/site/logo.png
# Build settings
version: v1.1
markdown: kramdown
exclude:
  - "README.md"
  - "BACKLOG.md"
  - "Makefile"
  - "Containerfile"
  - ".yolo-build"
  - "src/"
  - "docs/"
  - "index.md.backup"
  - "_config.yml.backup"
sass:
  style: compressed
