# Site settings
title: Yolo, a loveable single page theme
tag_text: Yolo
description: A loveable single page theme
# Site customizations
logo: assets/images/site/logo.png
style: corbs
# Build settings
version: v1.6
markdown: kramdown
exclude:
  - "README.md"
  - "BACKLOG.md"
  - "Makefile"
  - "Containerfile"
  - ".site-build"
  - "src/"
sass:
  style: compressed
