# Site settings
title: Yolo, a single page theme
tag_text: Yolo
description: A single pager theme
# Site customizations
logo: assets/images/logo.png
style: light
# Build settings
version: v1.4
sampler: false
markdown: kramdown
exclude:
  - "README.md"
  - "Makefile"
  - "sampler.Containerfile"
  - "yolo.Containerfile"
  - ".site-build"
sass:
  style: compressed
