# -----------------------------------------------------------------------------
# Jekyll site settings, see _data/settings.yml for Yolo settings
# -----------------------------------------------------------------------------
# baseurl: The sub-path your site is hosted from, for example: /blog
# -----------------------------------------------------------------------------
baseurl: ""
# -----------------------------------------------------------------------------
# url: The protocol and hostname for your site, for example: https://corbs.io
# -----------------------------------------------------------------------------
url: ""
# -----------------------------------------------------------------------------
# markdown: The markdown processor to use, kramdown is the jekyll default.
# -----------------------------------------------------------------------------
markdown: kramdown
#kramdown:
#  syntax_highlighter: rouge
#  # Rouge Options › https://github.com/jneen/rouge#full-options
#  syntax_highlighter_opts:
#    css_class: highlight
#    span:
#      line_numbers: false
#    block:
#      line_numbers: true
#      start_line: 1
# -----------------------------------------------------------------------------
# exclude: List of files and folders to exclude from jekyll
# -----------------------------------------------------------------------------
exclude:
  - "README.md"
  - "Makefile"
  - "Containerfile"
  - "src/"
  - "docs/"
# -----------------------------------------------------------------------------
# sass_dir: Folder that contains sass/scss files to be processed
# style: compressed or expanded css generation
# -----------------------------------------------------------------------------
sass:
  sass_dir: _sass
  style: compressed
  sourcemap: always
