# Site settings
title: Yolo, a single page theme
tag_text: Yolo
description: A single pager theme
# Site customizations
logo: assets/images/site/logo.png
style: corbs
# Build settings
version: v1.5
markdown: kramdown
exclude:
  - "README.md"
  - "Makefile"
  - "Containerfile"
  - ".site-build"
  - "src/"
sass:
  style: compressed
