# -----------------------------------------------------------------------------
# Yolo site settings. see: _config.yml for jekyll settings
# -----------------------------------------------------------------------------
name: Yolo
version: v1.3
title: Yolo on my friend
description: Loveable single pages
brand:
  theme: bubblegum
  syntax: domino
align: left
# header:
#  logo: assets/images/logo.png
sidebar:
  logo: assets/images/logo.png