# -----------------------------------------------------------------------------
# Yolo site settings. see: _config.yml for jekyll settings
# -----------------------------------------------------------------------------
name: Yolo
version: v1.3
title: Yolo on my friend
description: Loveable single pages
theme:
  name: corbs
  syntax:
    light: syntax-on-dark
    dark: syntax-on-dark
align: left
#header:
#  logo: assets/images/logo.png
sidebar:
  logo: assets/images/logo.png