# -----------------------------------------------------------------------------
# Yolo site settings. see: _config.yml for jekyll settings
# -----------------------------------------------------------------------------
name: Yolo
version: v1.3
title: Yolo Skeletor Theme
description: A nod to that 80s villain
theme:
  name: skeletor
align: left
#header:
#  logo: assets/images/logo.png
sidebar:
  logo: assets/images/logo.png