# -----------------------------------------------------------------------------
# Yolo site settings. see: _config.yml for jekyll settings
# -----------------------------------------------------------------------------
name: Dallas is a jewel
version: v1.3
title: Dallas is a jewel
description: Dallas is a beautiful sight...
theme:
  name: neon
  syntax: neon
align: left
header:
  logo: assets/images/logo.png
#sidebar:
#  logo: assets/images/logo.png