# Site settings
name: UBI one-pager
title: UBI one-pager
description: A handbook for working with UBI containers
# Site customizations
style: corbs
# Align content, left, center or right (default is left)
align: left
#header:
#  logo: assets/images/site/logo.png
#sidebar:
#  logo: assets/images/site/logo.png
# Build settings
version: v1.3
markdown: kramdown
exclude:
  - "README.md"
  - "Makefile"
  - "Containerfile"
  - "src/"
  - "docs/"
sass:
  style: compressed
