name: Weekly
title: Weekly
description: Status Report
style: weekly
align: left
#header:
#  logo: assets/images/logo.png
sidebar:
  logo: assets/images/logo.png
# Build settings
version: v1.3
markdown: kramdown
exclude:
  - "README.md"
  - "Makefile"
  - "Containerfile"
  - "src/"
  - "docs/"
sass:
  style: compressed