# Site settings
name: Yolo
title: Yolo skeletor theme
description: Skeletor theme sample page
style: skeletor
align: left
sidebar:
  logo: assets/images/logo.png
# Build settings
version: v1.3
markdown: kramdown
exclude:
  - "README.md"
  - "Makefile"
  - "Containerfile"
  - "src/"
  - "docs/"
sass:
  style: compressed
