# Site settings
name: Yolo
title: Yolo, a loveable single page theme
description: A loveable single page theme
# Site customizations
style: bookworm
header:
  logo: assets/images/logo.png
sidebar:
  logo: assets/images/logo.png
# Build settings
version: v1.12
markdown: kramdown
exclude:
  - "README.md"
  - "BACKLOG.md"
  - "Makefile"
  - "Containerfile"
  - ".yolo-build"
  - "src/"
  - "docs/"
  - "index.md.backup"
  - "_config.yml.backup"
sass:
  style: compressed
